// Optional OTel-backed Observer for the Polaris canary adapter (OPT-IN, kitex).
//
// Generated by `ncgo add infra polaris_adapter`. It implements release.Observer
// (defined in ops.go, same package) on top of the OpenTelemetry metric API. The
// generated kitex base template already wires go-framework OTLP and registers a
// global meter provider, so otel.Meter("ncgo.canary") is production-ready.
//
// Credentials are never emitted as metric labels or log fields.
//
// Required dependencies (already present in generated kitex projects via
// go-framework OTLP):
//
//	go.opentelemetry.io/otel
//	go.opentelemetry.io/otel/metric

package release

import (
	"context"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"
)

// OTelObserver reports decision-level canary metrics via the OTel metric API.
type OTelObserver struct {
	decision    metric.Int64Counter
	fallback    metric.Int64Counter
	discErr     metric.Int64Counter
	ruleErr     metric.Int64Counter
	poolStable  metric.Int64Gauge
	poolCanary  metric.Int64Gauge
	poolUnknown metric.Int64Gauge
}

// NewOTelObserver builds an Observer on the given meter. Pass nil to use the
// global meter (otel.Meter). Metrics are scoped under "ncgo.canary".
func NewOTelObserver(meter metric.Meter) (*OTelObserver, error) {
	if meter == nil {
		meter = otel.Meter("ncgo.canary")
	}
	o := &OTelObserver{}
	var err error
	if o.decision, err = meter.Int64Counter("ncgo.canary.decision", metric.WithDescription("canary routing decisions")); err != nil {
		return nil, err
	}
	if o.fallback, err = meter.Int64Counter("ncgo.canary.fallback", metric.WithDescription("canary fallback events")); err != nil {
		return nil, err
	}
	if o.discErr, err = meter.Int64Counter("ncgo.canary.discovery_error", metric.WithDescription("discovery failures")); err != nil {
		return nil, err
	}
	if o.ruleErr, err = meter.Int64Counter("ncgo.canary.rule_error", metric.WithDescription("rule load failures")); err != nil {
		return nil, err
	}
	if o.poolStable, err = meter.Int64Gauge("ncgo.canary.pool_size", metric.WithDescription("instance pool size (track=stable)")); err != nil {
		return nil, err
	}
	if o.poolCanary, err = meter.Int64Gauge("ncgo.canary.pool_size_canary", metric.WithDescription("instance pool size (track=canary)")); err != nil {
		return nil, err
	}
	if o.poolUnknown, err = meter.Int64Gauge("ncgo.canary.pool_size_unknown", metric.WithDescription("instance pool size (track=unknown)")); err != nil {
		return nil, err
	}
	return o, nil
}

func (o *OTelObserver) ObserveDecision(service string, d Decision, pools Pools) {
	ctx := context.Background()
	attrs := metric.WithAttributes(
		attribute.String("service", service),
		attribute.String("track", d.Track),
		attribute.String("reason", d.Reason),
	)
	o.decision.Add(ctx, 1, attrs)
	o.poolStable.Record(ctx, int64(len(pools.Stable)), metric.WithAttributes(attribute.String("service", service)))
	o.poolCanary.Record(ctx, int64(len(pools.Canary)), metric.WithAttributes(attribute.String("service", service)))
	o.poolUnknown.Record(ctx, int64(len(pools.Unknown)), metric.WithAttributes(attribute.String("service", service)))
}

func (o *OTelObserver) ObserveFallback(service, reason string) {
	o.fallback.Add(context.Background(), 1, metric.WithAttributes(attribute.String("service", service), attribute.String("reason", reason)))
}

func (o *OTelObserver) ObserveDiscovery(service string, _ int, err error) {
	if err != nil {
		o.discErr.Add(context.Background(), 1, metric.WithAttributes(attribute.String("service", service)))
	}
}

func (o *OTelObserver) ObserveRules(service string, _ int, err error) {
	if err != nil {
		o.ruleErr.Add(context.Background(), 1, metric.WithAttributes(attribute.String("service", service)))
	}
}
