// Code initially generated by ncgo add domain. Edit freely; ncgo will not
// overwrite this file unless --force is passed.
//
// ncgo:domain=device kind=register
package data

import (
	"github.com/samber/do"

	devicerepo "github.com/x/demo/internal/repository/device"
	deviceuc "github.com/x/demo/internal/usecase/device"
)

// RegisterDevice wires the device domain (repository + usecase) into the injector.
// Call this once during application bootstrap, before resolving handlers.
//
// ncgo:domain=device kind=register
func RegisterDevice(injector *do.Injector) {
	do.Provide(injector, func(i *do.Injector) (devicerepo.Repository, error) {
		return devicerepo.NewStub(), nil
	})
	do.Provide(injector, func(i *do.Injector) (*deviceuc.UseCase, error) {
		return deviceuc.New(do.MustInvoke[devicerepo.Repository](i)), nil
	})
}
