// Optional Polaris canary adapter for Kitex services (OPT-IN).
//
// Generated by `ncgo add infra polaris_adapter`. It wires the real polaris-go
// SDK into the SDK-neutral canary seams in canary.go (same package). ncgo never
// imports polaris-go; this file is the only SDK-coupled surface.
//
// Enable:
//
//	go get github.com/polarismesh/polaris-go
//	go get gopkg.in/yaml.v3
//
// Credentials are read from the environment only — never hardcode them:
//
//	POLARIS_TOKEN      Polaris auth token (empty = no auth)
//	POLARIS_NAMESPACE  default namespace when cfg.Namespace is empty
//
// Tested with polaris-go v1.7.1 (see scripts/verify-polaris-adapter.sh).

package release

import (
	"context"
	"os"

	polaris "github.com/polarismesh/polaris-go"
	"github.com/polarismesh/polaris-go/pkg/config"
	"github.com/polarismesh/polaris-go/pkg/model"
	"gopkg.in/yaml.v3"

	goerror "github.com/byx-darwin/go-tools/go-common/error"
)

// polarisAPI isolates every polaris-go call so mapping/parse/credential logic
// stays pure and unit-testable; only sdkClient couples to the SDK.
type polarisAPI interface {
	listInstances(ctx context.Context, cfg PolarisDiscoveryConfig) ([]PolarisInstance, error)
	loadRuleBytes(ctx context.Context, cfg PolarisRuleConfig) ([]byte, error)
}

// NewPolarisInstanceLister returns a PolarisInstanceLister backed by polaris-go.
// Construction fails fast when addresses are missing so misconfiguration is loud.
func NewPolarisInstanceLister(cfg PolarisDiscoveryConfig) (PolarisInstanceLister, error) {
	client, err := newSDKClient(cfg.Addresses)
	if err != nil {
		return nil, err
	}
	return func(ctx context.Context, c PolarisDiscoveryConfig) ([]PolarisInstance, error) {
		return client.listInstances(ctx, c)
	}, nil
}

// NewPolarisRuleLoader returns a PolarisRuleLoader that reads a canary RuleSet
// (YAML) from Polaris config.
func NewPolarisRuleLoader(cfg PolarisRuleConfig) (PolarisRuleLoader, error) {
	client, err := newSDKClient(cfg.Addresses)
	if err != nil {
		return nil, err
	}
	return func(ctx context.Context, c PolarisRuleConfig) (RuleSet, error) {
		raw, err := client.loadRuleBytes(ctx, c)
		if err != nil {
			return RuleSet{}, err
		}
		var rs RuleSet
		if err := yaml.Unmarshal(raw, &rs); err != nil {
			return RuleSet{}, goerror.In("release.polaris").Code("rule_parse_failed").Public("canary rules are invalid").Wrap(err)
		}
		return rs, nil
	}, nil
}

// NewPolarisSelector assembles a release.Selector wired to real Polaris
// discovery + rule loading.
func NewPolarisSelector(discoveryCfg PolarisDiscoveryConfig, ruleCfg PolarisRuleConfig) (Selector, error) {
	lister, err := NewPolarisInstanceLister(discoveryCfg)
	if err != nil {
		return Selector{}, err
	}
	loader, err := NewPolarisRuleLoader(ruleCfg)
	if err != nil {
		return Selector{}, err
	}
	return Selector{
		ServiceName:  firstNonEmpty(discoveryCfg.Service, ruleCfg.FileName),
		Discoverer:   PolarisDiscoverer{Config: discoveryCfg, ListInstances: lister},
		RuleProvider: PolarisRuleProvider{Config: ruleCfg, LoadRules: loader},
	}, nil
}

// sdkClient is the ONLY polaris-go-coupled implementation of polarisAPI.
// It holds a polaris ConsumerAPI (service discovery) and ConfigAPI (config
// file reads) built from a shared Configuration so addresses and auth are
// configured exactly once.
type sdkClient struct {
	consumer  polaris.ConsumerAPI
	configAPI polaris.ConfigAPI
}

func newSDKClient(addresses []string) (*sdkClient, error) {
	if len(addresses) == 0 {
		return nil, goerror.In("release.polaris").Code("config_invalid").Public("polaris configuration is invalid").New("addresses is empty")
	}
	cfg := config.NewDefaultConfiguration(addresses)
	if token := os.Getenv("POLARIS_TOKEN"); token != "" {
		// polaris-go reads auth from config; token value is never logged.
		cfg.GetGlobal().GetServerConnector().SetToken(token)
	}
	consumer, err := polaris.NewConsumerAPIByConfig(cfg)
	if err != nil {
		return nil, goerror.In("release.polaris").Code("sdk_init_failed").Public("polaris client init failed").Wrap(err)
	}
	configAPI, err := polaris.NewConfigAPIByConfig(cfg)
	if err != nil {
		consumer.Destroy()
		return nil, goerror.In("release.polaris").Code("sdk_init_failed").Public("polaris client init failed").Wrap(err)
	}
	return &sdkClient{consumer: consumer, configAPI: configAPI}, nil
}

func (c *sdkClient) listInstances(_ context.Context, cfg PolarisDiscoveryConfig) ([]PolarisInstance, error) {
	ns := firstNonEmpty(cfg.Namespace, os.Getenv("POLARIS_NAMESPACE"), "default")
	req := &polaris.GetAllInstancesRequest{}
	req.Namespace = ns
	req.Service = cfg.Service
	resp, err := c.consumer.GetAllInstances(req)
	if err != nil {
		return nil, goerror.In("release.polaris").Code("list_instances_failed").Public("polaris discovery failed").Wrap(err)
	}
	out := make([]PolarisInstance, 0, len(resp.GetInstances()))
	for _, ins := range resp.GetInstances() {
		out = append(out, instanceFromPolaris(ins, ns, cfg.Service))
	}
	return out, nil
}

func (c *sdkClient) loadRuleBytes(_ context.Context, cfg PolarisRuleConfig) ([]byte, error) {
	ns := firstNonEmpty(cfg.Namespace, os.Getenv("POLARIS_NAMESPACE"), "default")
	file, err := c.configAPI.GetConfigFile(ns, cfg.Group, cfg.FileName)
	if err != nil {
		return nil, goerror.In("release.polaris").Code("load_rules_failed").Public("polaris rule load failed").Wrap(err)
	}
	return []byte(file.GetContent()), nil
}

// instanceFromPolaris maps a polaris-go instance to the SDK-neutral model,
// preserving release.track metadata so canary pools resolve correctly.
func instanceFromPolaris(ins model.Instance, namespace, service string) PolarisInstance {
	meta := map[string]string{}
	for k, v := range ins.GetMetadata() {
		meta[k] = v
	}
	return PolarisInstance{
		ID:        ins.GetId(),
		Namespace: namespace,
		Service:   service,
		Host:      ins.GetHost(),
		Port:      int(ins.GetPort()),
		Weight:    int(ins.GetWeight()),
		Healthy:   ins.IsHealthy(),
		Isolate:   ins.IsIsolated(),
		Metadata:  meta,
	}
}
