package domain

import "fmt"

// Templates are kept as in-package fmt.Sprintf calls instead of text/template
// because they have a very small parameter surface (module + name + Export)
// and we want the rendered Go source to be obvious when reading the package.
//
// Every generated file carries `ncgo:domain=<name> kind=<layer>` anchors per
// PRD §7 so future commands (`ncgo add method`, `ncgo extract`) can locate
// the right struct without parsing free-form comments.

func renderUseCase(module, name string) []byte {
	src := fmt.Sprintf(`// Package %s implements the %s domain usecase layer.
//
// ncgo:domain=%s kind=usecase
package %s

import (
	%srepo "%s/internal/repository/%s"
)

// UseCase is the entry point for the %s domain.
//
// ncgo:domain=%s kind=usecase
type UseCase struct {
	repo %srepo.Repository
}

// New constructs a UseCase wired to the given Repository.
func New(repo %srepo.Repository) *UseCase {
	return &UseCase{repo: repo}
}

// Repo returns the underlying Repository. Callers should prefer adding
// methods on UseCase rather than reaching through this accessor.
func (u *UseCase) Repo() %srepo.Repository {
	return u.repo
}

// ncgo:methods:start
// ncgo:methods:end
`,
		name, name,
		name,
		name,
		name, module, name,
		name,
		name,
		name,
		name,
		name,
	)
	return []byte(src)
}

func renderRepository(name string) []byte {
	export := exportName(name)
	src := fmt.Sprintf(`// Package %srepo is the data port for the %s domain.
//
// The interface lives here; concrete adapters (postgres, in-memory, redis)
// register themselves with samber/do in internal/base/data.
//
// ncgo:domain=%s kind=repository
package %srepo

// Repository is the %s domain port.
//
// ncgo:domain=%s kind=repository
type Repository interface {
	// ncgo:methods:start
	// ncgo:methods:end
}

// Stub is an in-memory Repository implementation suitable for tests and
// for booting a service before a real adapter is wired up. Replace with a
// concrete adapter once the domain ships.
//
// ncgo:domain=%s kind=stub
type Stub struct{}

// NewStub returns a Stub Repository.
func NewStub() *Stub { return &Stub{} }

// Compile-time assertion that Stub implements Repository.
var _ Repository = (*Stub)(nil)

// %s is exposed so callers can refer to the domain export name without
// hard-coding the string. It is intentionally a no-op symbol.
const %s = "%s"
`,
		name, name,
		name,
		name,
		name,
		name,
		name,
		export,
		export,
		export,
	)
	return []byte(src)
}

func renderRegister(module, name string) []byte {
	export := exportName(name)
	src := fmt.Sprintf(`// Code initially generated by ncgo add domain. Edit freely; ncgo will not
// overwrite this file unless --force is passed.
//
// ncgo:domain=%s kind=register
package data

import (
	"github.com/samber/do"

	%srepo "%s/internal/repository/%s"
	%suc "%s/internal/usecase/%s"
)

// Register%s wires the %s domain (repository + usecase) into the injector.
// Call this once during application bootstrap, before resolving handlers.
//
// ncgo:domain=%s kind=register
func Register%s(injector *do.Injector) {
	do.Provide(injector, func(i *do.Injector) (%srepo.Repository, error) {
		return %srepo.NewStub(), nil
	})
	do.Provide(injector, func(i *do.Injector) (*%suc.UseCase, error) {
		return %suc.New(do.MustInvoke[%srepo.Repository](i)), nil
	})
}
`,
		name,
		name, module, name,
		name, module, name,
		export, name,
		name,
		export,
		name,
		name,
		name,
		name,
		name,
	)
	return []byte(src)
}

// exportName converts a snake_case domain name to PascalCase for use as a Go
// identifier. The package's own nameRE forbids hyphens so we only need to
// handle underscores here.
func exportName(s string) string {
	out := make([]byte, 0, len(s))
	upper := true
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c == '_' {
			upper = true
			continue
		}
		if upper && c >= 'a' && c <= 'z' {
			c -= 'a' - 'A'
		}
		out = append(out, c)
		upper = false
	}
	return string(out)
}
