package cli

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/cobra"

	"github.com/byx-darwin/ncgo/internal/manifest"
)

// mustWriteFile fails the test if writing to path errors. Test setup that
// cannot create its fixture cannot meaningfully proceed.
func mustWriteFile(t *testing.T, path string, data []byte) {
	t.Helper()
	if err := os.WriteFile(path, data, 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

// mustMkdirAll fails the test if creating the directory tree errors.
func mustMkdirAll(t *testing.T, path string) {
	t.Helper()
	if err := os.MkdirAll(path, 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", path, err)
	}
}

func TestImportDryRun(t *testing.T) {
	dir := t.TempDir()
	mustWriteFile(t, filepath.Join(dir, "go.mod"), []byte("module github.com/test/myapp\n\ngo 1.25\n"))
	mustWriteFile(t, filepath.Join(dir, "router.go"), []byte("// Code generated by hz. DO NOT EDIT.\npackage main\n"))

	var out bytes.Buffer
	cmd := &cobra.Command{}
	cmd.SetOut(&out)

	opts := &importOptions{Root: dir, DryRun: true}
	err := runImport(opts)(cmd, nil)
	if err != nil {
		t.Fatalf("runImport dry-run: %v", err)
	}

	output := out.String()
	if !strings.Contains(output, "Preview of generated manifest") {
		t.Fatalf("dry-run output missing preview header:\n%s", output)
	}
	if !strings.Contains(output, "github.com/test/myapp") {
		t.Fatalf("dry-run output missing module path:\n%s", output)
	}
	if !strings.Contains(output, "kind: hertz") {
		t.Fatalf("dry-run output missing kind:\n%s", output)
	}

	// Verify no manifest was written.
	if _, err := os.Stat(manifest.Path(dir)); !os.IsNotExist(err) {
		t.Fatalf("dry-run should not write manifest, but found one at %s", manifest.Path(dir))
	}
}

func TestImportRejectsExistingManifest(t *testing.T) {
	dir := t.TempDir()
	mustWriteFile(t, filepath.Join(dir, "go.mod"), []byte("module github.com/test/myapp\n\ngo 1.25\n"))
	mustWriteFile(t, filepath.Join(dir, "router.go"), []byte("// Code generated by hz. DO NOT EDIT.\npackage main\n"))
	mustMkdirAll(t, filepath.Join(dir, ".ncgo"))
	mustWriteFile(t, filepath.Join(dir, ".ncgo", "manifest.yaml"), []byte("ncgo:\n  version: 0.1.0-dev\n"))

	opts := &importOptions{Root: dir}
	err := runImport(opts)(nil, nil)
	if err == nil {
		t.Fatal("runImport should reject when manifest already exists")
	}
	if !strings.Contains(err.Error(), "manifest already exists") {
		t.Fatalf("error = %q, want 'manifest already exists'", err.Error())
	}
}

func TestImportRejectsMissingGoMod(t *testing.T) {
	dir := t.TempDir()

	opts := &importOptions{Root: dir}
	err := runImport(opts)(nil, nil)
	if err == nil {
		t.Fatal("runImport should reject when go.mod is missing")
	}
	if !strings.Contains(err.Error(), "go.mod not found") {
		t.Fatalf("error = %q, want 'go.mod not found'", err.Error())
	}
}

func TestImportFullWrite(t *testing.T) {
	dir := t.TempDir()
	mustWriteFile(t, filepath.Join(dir, "go.mod"), []byte("module github.com/test/myapp\n\ngo 1.25\n"))
	mustWriteFile(t, filepath.Join(dir, "handler.go"), []byte("// Code generated by kitex. DO NOT EDIT.\npackage main\n\nfunc main() {\n    svr := userservice.NewServer(new(UserServiceImpl))\n}\n"))

	var out bytes.Buffer
	cmd := &cobra.Command{}
	cmd.SetOut(&out)

	opts := &importOptions{Root: dir}
	err := runImport(opts)(cmd, nil)
	if err != nil {
		t.Fatalf("runImport: %v", err)
	}

	output := out.String()
	if !strings.Contains(output, "Created .ncgo/manifest.yaml") {
		t.Fatalf("output missing success message:\n%s", output)
	}
	if !strings.Contains(output, "ncgo doctor") {
		t.Fatalf("output missing next steps:\n%s", output)
	}

	// Load and validate the written manifest.
	m, err := manifest.Load(dir)
	if err != nil {
		t.Fatalf("manifest.Load(): %v", err)
	}
	if m.Module != "github.com/test/myapp" {
		t.Fatalf("manifest.Module = %q, want %q", m.Module, "github.com/test/myapp")
	}
	if m.Service.Kind != manifest.KindKitex {
		t.Fatalf("manifest.Service.Kind = %q, want %q", m.Service.Kind, manifest.KindKitex)
	}
	if m.Mode != manifest.ModeMono {
		t.Fatalf("manifest.Mode = %q, want %q", m.Mode, manifest.ModeMono)
	}
	if m.Service.Name != "userservice" {
		t.Fatalf("manifest.Service.Name = %q, want %q", m.Service.Name, "userservice")
	}
	if m.Service.WithDatabase {
		t.Fatal("manifest.Service.WithDatabase should be false")
	}
}

func TestImportExplicitKind(t *testing.T) {
	dir := t.TempDir()
	mustWriteFile(t, filepath.Join(dir, "go.mod"), []byte("module github.com/test/myapp\n\ngo 1.25\n"))
	mustWriteFile(t, filepath.Join(dir, "handler.go"), []byte("// Code generated by kitex. DO NOT EDIT.\npackage main\n"))

	var out bytes.Buffer
	cmd := &cobra.Command{}
	cmd.SetOut(&out)

	// Explicit kitex even though there's a handler.go; should still work.
	opts := &importOptions{Root: dir, Kind: manifest.KindKitex}
	err := runImport(opts)(cmd, nil)
	if err != nil {
		t.Fatalf("runImport with explicit kind: %v", err)
	}
}

func TestImportInvalidKind(t *testing.T) {
	dir := t.TempDir()
	mustWriteFile(t, filepath.Join(dir, "go.mod"), []byte("module github.com/test/myapp\n\ngo 1.25\n"))
	mustWriteFile(t, filepath.Join(dir, "handler.go"), []byte("// Code generated by kitex. DO NOT EDIT.\npackage main\n"))

	opts := &importOptions{Root: dir, Kind: "grpc"}
	err := runImport(opts)(nil, nil)
	if err == nil {
		t.Fatal("runImport should reject invalid --kind")
	}
	if !strings.Contains(err.Error(), "invalid") {
		t.Fatalf("error = %q, want 'invalid'", err.Error())
	}
}

func TestImportNoDetectableKind(t *testing.T) {
	dir := t.TempDir()
	mustWriteFile(t, filepath.Join(dir, "go.mod"), []byte("module github.com/test/myapp\n\ngo 1.25\n"))
	// No router.go or handler.go markers.

	opts := &importOptions{Root: dir}
	err := runImport(opts)(nil, nil)
	if err == nil {
		t.Fatal("runImport should reject when kind cannot be detected")
	}
	if !strings.Contains(err.Error(), "cannot detect service kind") {
		t.Fatalf("error = %q, want 'cannot detect service kind'", err.Error())
	}
}

func TestRootCmdIncludesImportCommand(t *testing.T) {
	cmd, _, err := newRootCmd().Find([]string{"import"})
	if err != nil {
		t.Fatalf("Find import: %v", err)
	}
	if cmd == nil || cmd.Name() != "import" {
		t.Fatal("import command not registered")
	}
}

func TestImportHelpDocumentsKindDetection(t *testing.T) {
	cmd := newImportCmd()
	if !strings.Contains(cmd.Long, "marker") {
		t.Errorf("import Long help should mention generator marker files:\n%s", cmd.Long)
	}
	if !strings.Contains(cmd.Long, "--kind") {
		t.Errorf("import Long help should mention explicit --kind for marker-less scaffolds:\n%s", cmd.Long)
	}
}
