package cli

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/cobra"

	"github.com/byx-darwin/ncgo/internal/manifest"
)

func TestDetectModule(t *testing.T) {
	dir := t.TempDir()

	t.Run("extracts module path from go.mod", func(t *testing.T) {
		os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module github.com/test/myapp\n\ngo 1.25\n"), 0o644)
		got, err := detectModule(dir)
		if err != nil {
			t.Fatalf("detectModule() error = %v", err)
		}
		if got != "github.com/test/myapp" {
			t.Fatalf("detectModule() = %q, want %q", got, "github.com/test/myapp")
		}
	})

	t.Run("errors when go.mod is missing", func(t *testing.T) {
		empty := t.TempDir()
		_, err := detectModule(empty)
		if err == nil {
			t.Fatal("detectModule() should error when go.mod is missing")
		}
	})

	t.Run("errors when go.mod has no module directive", func(t *testing.T) {
		d := t.TempDir()
		os.WriteFile(filepath.Join(d, "go.mod"), []byte("go 1.25\n"), 0o644)
		_, err := detectModule(d)
		if err == nil {
			t.Fatal("detectModule() should error when no module directive")
		}
		if !strings.Contains(err.Error(), "module directive not found") {
			t.Fatalf("error = %q, want 'module directive not found'", err.Error())
		}
	})
}

func TestDetectKind(t *testing.T) {
	t.Run("detects hertz from router.go marker", func(t *testing.T) {
		dir := t.TempDir()
		os.WriteFile(filepath.Join(dir, "router.go"), []byte("// Code generated by hz. DO NOT EDIT.\npackage main\n"), 0o644)
		got, err := detectKind(dir)
		if err != nil {
			t.Fatalf("detectKind() error = %v", err)
		}
		if got != manifest.KindHertz {
			t.Fatalf("detectKind() = %q, want %q", got, manifest.KindHertz)
		}
	})

	t.Run("detects kitex from handler.go marker", func(t *testing.T) {
		dir := t.TempDir()
		os.WriteFile(filepath.Join(dir, "handler.go"), []byte("// Code generated by kitex. DO NOT EDIT.\npackage main\n"), 0o644)
		got, err := detectKind(dir)
		if err != nil {
			t.Fatalf("detectKind() error = %v", err)
		}
		if got != manifest.KindKitex {
			t.Fatalf("detectKind() = %q, want %q", got, manifest.KindKitex)
		}
	})

	t.Run("errors when neither marker is found", func(t *testing.T) {
		dir := t.TempDir()
		_, err := detectKind(dir)
		if err == nil {
			t.Fatal("detectKind() should error when no markers found")
		}
		if !strings.Contains(err.Error(), "cannot detect service kind") {
			t.Fatalf("error = %q, want 'cannot detect service kind'", err.Error())
		}
	})

	t.Run("prefers hertz when both markers exist", func(t *testing.T) {
		dir := t.TempDir()
		os.WriteFile(filepath.Join(dir, "router.go"), []byte("// Code generated by hz. DO NOT EDIT.\npackage main\n"), 0o644)
		os.WriteFile(filepath.Join(dir, "handler.go"), []byte("// Code generated by kitex. DO NOT EDIT.\npackage main\n"), 0o644)
		got, err := detectKind(dir)
		if err != nil {
			t.Fatalf("detectKind() error = %v", err)
		}
		if got != manifest.KindHertz {
			t.Fatalf("detectKind() = %q, want %q (hertz checked first)", got, manifest.KindHertz)
		}
	})
}

func TestDetectServiceName(t *testing.T) {
	t.Run("from IDL file", func(t *testing.T) {
		dir := t.TempDir()
		os.MkdirAll(filepath.Join(dir, "idl", "app"), 0o755)
		os.WriteFile(filepath.Join(dir, "idl", "app", "user-api.proto"), []byte("syntax = \"proto3\";\n"), 0o644)
		got, err := detectServiceName(dir, manifest.KindHertz)
		if err != nil {
			t.Fatalf("detectServiceName() error = %v", err)
		}
		if got != "user-api" {
			t.Fatalf("detectServiceName() = %q, want %q", got, "user-api")
		}
	})

	t.Run("from IDL in idl/ root", func(t *testing.T) {
		dir := t.TempDir()
		os.MkdirAll(filepath.Join(dir, "idl"), 0o755)
		os.WriteFile(filepath.Join(dir, "idl", "myservice.proto"), []byte("syntax = \"proto3\";\n"), 0o644)
		got, err := detectServiceName(dir, manifest.KindHertz)
		if err != nil {
			t.Fatalf("detectServiceName() error = %v", err)
		}
		if got != "myservice" {
			t.Fatalf("detectServiceName() = %q, want %q", got, "myservice")
		}
	})

	t.Run("from kitex handler NewServer call", func(t *testing.T) {
		dir := t.TempDir()
		os.WriteFile(filepath.Join(dir, "handler.go"), []byte("// Code generated by kitex.\npackage main\n\nfunc main() {\n    svr := userservice.NewServer(new(UserServiceImpl))\n}\n"), 0o644)
		got, err := detectServiceName(dir, manifest.KindKitex)
		if err != nil {
			t.Fatalf("detectServiceName() error = %v", err)
		}
		if got != "userservice" {
			t.Fatalf("detectServiceName() = %q, want %q", got, "userservice")
		}
	})

	t.Run("fallback to directory name", func(t *testing.T) {
		dir := t.TempDir()
		// Create a subdir with a specific name.
		sub := filepath.Join(dir, "myfallback")
		os.MkdirAll(sub, 0o755)
		got, err := detectServiceName(sub, manifest.KindHertz)
		if err != nil {
			t.Fatalf("detectServiceName() error = %v", err)
		}
		if got != "myfallback" {
			t.Fatalf("detectServiceName() = %q, want %q", got, "myfallback")
		}
	})
}

func TestDetectIDLPath(t *testing.T) {
	t.Run("prioritizes idl/app/<name>.proto", func(t *testing.T) {
		dir := t.TempDir()
		os.MkdirAll(filepath.Join(dir, "idl", "app"), 0o755)
		os.WriteFile(filepath.Join(dir, "idl", "app", "user-api.proto"), []byte("syntax = \"proto3\";\n"), 0o644)
		os.WriteFile(filepath.Join(dir, "idl", "other.thrift"), []byte("namespace go other\n"), 0o644)
		got := detectIDLPath(dir, "user-api")
		if got != "idl/app/user-api.proto" {
			t.Fatalf("detectIDLPath() = %q, want %q", got, "idl/app/user-api.proto")
		}
	})

	t.Run("scans idl/ directory when no service name", func(t *testing.T) {
		dir := t.TempDir()
		os.MkdirAll(filepath.Join(dir, "idl"), 0o755)
		os.WriteFile(filepath.Join(dir, "idl", "random.thrift"), []byte("namespace go r\n"), 0o644)
		got := detectIDLPath(dir, "")
		if got != "idl/random.thrift" {
			t.Fatalf("detectIDLPath() = %q, want %q", got, "idl/random.thrift")
		}
	})

	t.Run("returns empty when no IDL directory exists", func(t *testing.T) {
		dir := t.TempDir()
		got := detectIDLPath(dir, "nobody")
		if got != "" {
			t.Fatalf("detectIDLPath() = %q, want empty", got)
		}
	})
}

func TestServiceNameFromHertz(t *testing.T) {
	t.Run("extracts from biz/router import", func(t *testing.T) {
		dir := t.TempDir()
		os.WriteFile(filepath.Join(dir, "router.go"), []byte(
			"// Code generated by hz.\npackage main\n\nimport (\n    \"github.com/acme/user-api/biz/router\"\n)\n\nfunc main() { router.GeneratedRegister(nil) }\n",
		), 0o644)
		got := serviceNameFromHertz(dir)
		if got != "user-api" {
			t.Fatalf("serviceNameFromHertz() = %q, want %q", got, "user-api")
		}
	})

	t.Run("returns empty when no matching import", func(t *testing.T) {
		dir := t.TempDir()
		os.WriteFile(filepath.Join(dir, "router.go"), []byte(
			"// Code generated by hz.\npackage main\n\nfunc main() {}\n",
		), 0o644)
		got := serviceNameFromHertz(dir)
		if got != "" {
			t.Fatalf("serviceNameFromHertz() = %q, want empty", got)
		}
	})
}

func TestImportDryRun(t *testing.T) {
	dir := t.TempDir()
	os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module github.com/test/myapp\n\ngo 1.25\n"), 0o644)
	os.WriteFile(filepath.Join(dir, "router.go"), []byte("// Code generated by hz. DO NOT EDIT.\npackage main\n"), 0o644)

	var out bytes.Buffer
	cmd := &cobra.Command{}
	cmd.SetOut(&out)

	opts := &importOptions{Root: dir, DryRun: true}
	err := runImport(opts)(cmd, nil)
	if err != nil {
		t.Fatalf("runImport dry-run: %v", err)
	}

	output := out.String()
	if !strings.Contains(output, "Preview of generated manifest") {
		t.Fatalf("dry-run output missing preview header:\n%s", output)
	}
	if !strings.Contains(output, "github.com/test/myapp") {
		t.Fatalf("dry-run output missing module path:\n%s", output)
	}
	if !strings.Contains(output, "kind: hertz") {
		t.Fatalf("dry-run output missing kind:\n%s", output)
	}

	// Verify no manifest was written.
	if _, err := os.Stat(manifest.Path(dir)); !os.IsNotExist(err) {
		t.Fatalf("dry-run should not write manifest, but found one at %s", manifest.Path(dir))
	}
}

func TestImportRejectsExistingManifest(t *testing.T) {
	dir := t.TempDir()
	os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module github.com/test/myapp\n\ngo 1.25\n"), 0o644)
	os.WriteFile(filepath.Join(dir, "router.go"), []byte("// Code generated by hz. DO NOT EDIT.\npackage main\n"), 0o644)
	os.MkdirAll(filepath.Join(dir, ".ncgo"), 0o755)
	os.WriteFile(filepath.Join(dir, ".ncgo", "manifest.yaml"), []byte("ncgo:\n  version: 0.1.0-dev\n"), 0o644)

	opts := &importOptions{Root: dir}
	err := runImport(opts)(nil, nil)
	if err == nil {
		t.Fatal("runImport should reject when manifest already exists")
	}
	if !strings.Contains(err.Error(), "manifest already exists") {
		t.Fatalf("error = %q, want 'manifest already exists'", err.Error())
	}
}

func TestImportRejectsMissingGoMod(t *testing.T) {
	dir := t.TempDir()

	opts := &importOptions{Root: dir}
	err := runImport(opts)(nil, nil)
	if err == nil {
		t.Fatal("runImport should reject when go.mod is missing")
	}
	if !strings.Contains(err.Error(), "go.mod not found") {
		t.Fatalf("error = %q, want 'go.mod not found'", err.Error())
	}
}

func TestImportFullWrite(t *testing.T) {
	dir := t.TempDir()
	os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module github.com/test/myapp\n\ngo 1.25\n"), 0o644)
	os.WriteFile(filepath.Join(dir, "handler.go"), []byte("// Code generated by kitex. DO NOT EDIT.\npackage main\n\nfunc main() {\n    svr := userservice.NewServer(new(UserServiceImpl))\n}\n"), 0o644)

	var out bytes.Buffer
	cmd := &cobra.Command{}
	cmd.SetOut(&out)

	opts := &importOptions{Root: dir}
	err := runImport(opts)(cmd, nil)
	if err != nil {
		t.Fatalf("runImport: %v", err)
	}

	output := out.String()
	if !strings.Contains(output, "Created .ncgo/manifest.yaml") {
		t.Fatalf("output missing success message:\n%s", output)
	}
	if !strings.Contains(output, "ncgo doctor") {
		t.Fatalf("output missing next steps:\n%s", output)
	}

	// Load and validate the written manifest.
	m, err := manifest.Load(dir)
	if err != nil {
		t.Fatalf("manifest.Load(): %v", err)
	}
	if m.Module != "github.com/test/myapp" {
		t.Fatalf("manifest.Module = %q, want %q", m.Module, "github.com/test/myapp")
	}
	if m.Service.Kind != manifest.KindKitex {
		t.Fatalf("manifest.Service.Kind = %q, want %q", m.Service.Kind, manifest.KindKitex)
	}
	if m.Mode != manifest.ModeMono {
		t.Fatalf("manifest.Mode = %q, want %q", m.Mode, manifest.ModeMono)
	}
	if m.Service.Name != "userservice" {
		t.Fatalf("manifest.Service.Name = %q, want %q", m.Service.Name, "userservice")
	}
	if m.Service.WithDatabase {
		t.Fatal("manifest.Service.WithDatabase should be false")
	}
}

func TestImportExplicitKind(t *testing.T) {
	dir := t.TempDir()
	os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module github.com/test/myapp\n\ngo 1.25\n"), 0o644)
	os.WriteFile(filepath.Join(dir, "handler.go"), []byte("// Code generated by kitex. DO NOT EDIT.\npackage main\n"), 0o644)

	var out bytes.Buffer
	cmd := &cobra.Command{}
	cmd.SetOut(&out)

	// Explicit kitex even though there's a handler.go; should still work.
	opts := &importOptions{Root: dir, Kind: manifest.KindKitex}
	err := runImport(opts)(cmd, nil)
	if err != nil {
		t.Fatalf("runImport with explicit kind: %v", err)
	}
}

func TestImportInvalidKind(t *testing.T) {
	dir := t.TempDir()
	os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module github.com/test/myapp\n\ngo 1.25\n"), 0o644)
	os.WriteFile(filepath.Join(dir, "handler.go"), []byte("// Code generated by kitex. DO NOT EDIT.\npackage main\n"), 0o644)

	opts := &importOptions{Root: dir, Kind: "grpc"}
	err := runImport(opts)(nil, nil)
	if err == nil {
		t.Fatal("runImport should reject invalid --kind")
	}
	if !strings.Contains(err.Error(), "invalid") {
		t.Fatalf("error = %q, want 'invalid'", err.Error())
	}
}

func TestImportNoDetectableKind(t *testing.T) {
	dir := t.TempDir()
	os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module github.com/test/myapp\n\ngo 1.25\n"), 0o644)
	// No router.go or handler.go markers.

	opts := &importOptions{Root: dir}
	err := runImport(opts)(nil, nil)
	if err == nil {
		t.Fatal("runImport should reject when kind cannot be detected")
	}
	if !strings.Contains(err.Error(), "cannot detect service kind") {
		t.Fatalf("error = %q, want 'cannot detect service kind'", err.Error())
	}
}

func TestServiceNameFromIDLStripsServicePrefix(t *testing.T) {
	// serviceNameFromIDL is tested indirectly via detectServiceName,
	// but exercise the prefix-stripping directly.
	got := serviceNameFromIDL("idl/app/service_user-api.proto")
	if got != "user-api" {
		t.Fatalf("serviceNameFromIDL() = %q, want %q", got, "user-api")
	}
}

func TestServiceNameFromKitex(t *testing.T) {
	dir := t.TempDir()
	os.WriteFile(filepath.Join(dir, "handler.go"), []byte(
		"// Code generated by kitex.\npackage main\n\nfunc main() {\n    svr := myservice.NewServer(new(ServiceImpl))\n}\n",
	), 0o644)
	got := serviceNameFromKitex(dir)
	if got != "myservice" {
		t.Fatalf("serviceNameFromKitex() = %q, want %q", got, "myservice")
	}
}

func TestRootCmdIncludesImportCommand(t *testing.T) {
	cmd, _, err := newRootCmd().Find([]string{"import"})
	if err != nil {
		t.Fatalf("Find import: %v", err)
	}
	if cmd == nil || cmd.Name() != "import" {
		t.Fatal("import command not registered")
	}
}

func TestImportHelpDocumentsKindDetection(t *testing.T) {
	cmd := newImportCmd()
	if !strings.Contains(cmd.Long, "marker") {
		t.Errorf("import Long help should mention generator marker files:\n%s", cmd.Long)
	}
	if !strings.Contains(cmd.Long, "--kind") {
		t.Errorf("import Long help should mention explicit --kind for marker-less scaffolds:\n%s", cmd.Long)
	}
}
