package cli

import (
	"fmt"
	"path/filepath"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"

	"github.com/byx-darwin/ncgo/internal/assets"
	"github.com/byx-darwin/ncgo/internal/importer"
	"github.com/byx-darwin/ncgo/internal/manifest"
)

type importOptions struct {
	Root   string
	Kind   string // auto-detected if empty
	DryRun bool
}

func newImportCmd() *cobra.Command {
	opts := &importOptions{}
	cmd := &cobra.Command{
		Use:   "import",
		Short: "Import an existing hz/kitex project into ncgo",
		Long: `Detect an existing Hertz or Kitex project and generate .ncgo/manifest.yaml.

ncgo import detects project type from generated markers in the source code,
extracts the Go module path from go.mod, and writes a minimal manifest.
This allows existing projects to use ncgo doctor, ncgo ai sync, and MCP tools.

Kind auto-detection looks for generator marker files: router.go containing
"// Code generated by hz." (Hertz) or handler.go containing
"// Code generated by kitex." (Kitex). Projects scaffolded with
` + "`ncgo new --no-generate`" + ` have not run the generators yet, so they have
no marker files; import such projects with an explicit --kind flag
(for example: ncgo import --root . --kind kitex).`,
		Example: `  ncgo import
  ncgo import --root ./my-service
  ncgo import --root . --dry-run`,
		RunE: runImport(opts),
	}
	cmd.Flags().StringVar(&opts.Root, "root", ".", "Project root")
	cmd.Flags().StringVar(&opts.Kind, "kind", "", "Service kind (hertz or kitex); auto-detected if empty")
	cmd.Flags().BoolVar(&opts.DryRun, "dry-run", false, "Preview without writing files")
	return cmd
}

func runImport(opts *importOptions) func(*cobra.Command, []string) error {
	return func(cmd *cobra.Command, args []string) error {
		m, err := importer.Detect(importer.Options{
			Root:          opts.Root,
			Kind:          opts.Kind,
			NCGOVersion:   Version,
			AssetsVersion: assets.Version(),
		})
		if err != nil {
			return fmt.Errorf("import: %w", err)
		}

		if opts.DryRun {
			out := cmd.OutOrStdout()
			fmt.Fprint(out, "Preview of generated manifest:\n\n")
			b, err := yaml.Marshal(m)
			if err != nil {
				return fmt.Errorf("import: marshal preview: %w", err)
			}
			fmt.Fprint(out, string(b))
			return nil
		}

		root, err := filepath.Abs(opts.Root)
		if err != nil {
			return fmt.Errorf("import: resolve root: %w", err)
		}
		if err := manifest.Save(root, m); err != nil {
			return fmt.Errorf("import: %w", err)
		}

		out := cmd.OutOrStdout()
		fmt.Fprintf(out, "✓ Created .ncgo/manifest.yaml\n\n")
		fmt.Fprintln(out, "Next steps:")
		fmt.Fprintln(out, "  ncgo doctor                    # Check project health")
		fmt.Fprintln(out, "  ncgo ai sync                   # Generate AI context files")
		fmt.Fprintln(out, "  ncgo add infra redis --dry-run # Preview optional infrastructure")
		return nil
	}
}
