package method

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/byx-darwin/ncgo/internal/manifest"
)

const kitexHandlerFixture = `// Code generated by kitex generator.

package demohandler

import (
	"context"

	"example.com/demo/internal/pkg/rpcerror"
	pb "example.com/demo/kitex_gen/demo"
	usecase "example.com/demo/internal/usecase/demo"
)

type DemoServiceImpl struct {
	uc *usecase.UseCase
}

func NewDemoServiceImpl(uc *usecase.UseCase) *DemoServiceImpl {
	return &DemoServiceImpl{uc: uc}
}

func (s *DemoServiceImpl) Ping(ctx context.Context, req *pb.PingReq) (resp *pb.PingResp, err error) {
	resp, err = s.uc.Ping(ctx, req)
	if err != nil {
		return nil, rpcerror.ToBizError(err)
	}
	return resp, nil
}
`

const hzHandlerFixture = `// Code generated by hertz generator.

package pb

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"

	pb "example.com/demo/internal/pb"
)

type Handler struct {
	uc useCase
}

type useCase interface {
	Ping(ctx context.Context, req *pb.PingReq) (*pb.PingResp, error)
}

func NewPbHandler(uc useCase) *Handler {
	return &Handler{uc: uc}
}

var _ = app.RequestContext{}
`

func seedRPCProject(t *testing.T, kind, handlerRelPath, handlerSrc, usecaseSrc string) string {
	t.Helper()
	root := t.TempDir()
	if err := manifest.Save(root, &manifest.Manifest{
		Ncgo:   manifest.Meta{Version: "0.3.0-test", AssetsVersion: "test"},
		Mode:   manifest.ModeMono,
		Module: "example.com/demo",
		Service: manifest.Service{
			Name: "demo", Kind: kind, IDL: "idl/app/demo.proto",
		},
		GeneratedAt: time.Date(2026, 4, 29, 8, 0, 0, 0, time.UTC),
	}); err != nil {
		t.Fatalf("seed manifest: %v", err)
	}
	handlerPath := filepath.Join(root, handlerRelPath)
	if err := os.MkdirAll(filepath.Dir(handlerPath), 0o755); err != nil {
		t.Fatalf("mkdir handler dir: %v", err)
	}
	if err := os.WriteFile(handlerPath, []byte(handlerSrc), 0o644); err != nil {
		t.Fatalf("write handler fixture: %v", err)
	}
	usecasePath := filepath.Join(root, "internal", "usecase", "demo", "usecase.go")
	if err := os.MkdirAll(filepath.Dir(usecasePath), 0o755); err != nil {
		t.Fatalf("mkdir usecase dir: %v", err)
	}
	if err := os.WriteFile(usecasePath, []byte(usecaseSrc), 0o644); err != nil {
		t.Fatalf("write usecase fixture: %v", err)
	}
	return root
}

const minimalUsecaseGo = `package demo

type UseCase struct{}

func New() *UseCase { return &UseCase{} }
`

// minimalUsecaseGoWithHeader mirrors the shape of a freshly scaffolded
// kitex usecase.go: a leading generated-file comment before the package
// clause, and no import block at all (no RPC methods added yet).
const minimalUsecaseGoWithHeader = `// Code generated by kitex generator. Edit business logic here.

package demo

type UseCase struct{}

func New() *UseCase { return &UseCase{} }
`

func TestAddRPCKitexAppendsSignature(t *testing.T) {
	root := seedRPCProject(t, manifest.KindKitex,
		"internal/handler/demo/handler.go", kitexHandlerFixture, minimalUsecaseGo)

	res, err := AddRPC(RPCOptions{Root: root, Service: "demo", RPC: "Ping"})
	if err != nil {
		t.Fatalf("AddRPC: %v", err)
	}
	if res.Service != "demo" || res.Method != "Ping" {
		t.Errorf("result = %+v", res)
	}
	body, err := os.ReadFile(res.Path)
	if err != nil {
		t.Fatalf("read usecase: %v", err)
	}
	s := string(body)
	for _, want := range []string{
		`pb "example.com/demo/kitex_gen/demo"`,
		`goerror "github.com/byx-darwin/go-tools/go-common/error"`,
		"func (uc *UseCase) Ping(ctx context.Context, req *pb.PingReq) (resp *pb.PingResp, err error) {",
		`Errorf("Ping: not implemented")`,
	} {
		if !strings.Contains(s, want) {
			t.Errorf("usecase.go missing %q\n---\n%s", want, s)
		}
	}
}

func TestAddRPCKitexAppendsSignatureToFreshlyScaffoldedFile(t *testing.T) {
	root := seedRPCProject(t, manifest.KindKitex,
		"internal/handler/demo/handler.go", kitexHandlerFixture, minimalUsecaseGoWithHeader)

	res, err := AddRPC(RPCOptions{Root: root, Service: "demo", RPC: "Ping"})
	if err != nil {
		t.Fatalf("AddRPC: %v", err)
	}
	body, err := os.ReadFile(res.Path)
	if err != nil {
		t.Fatalf("read usecase: %v", err)
	}
	s := string(body)

	pkgIdx := strings.Index(s, "package demo")
	importIdx := strings.Index(s, "import (")
	methodIdx := strings.Index(s, "func (uc *UseCase) Ping(")
	if pkgIdx < 0 || importIdx < 0 || methodIdx < 0 {
		t.Fatalf("usecase.go missing expected sections:\n---\n%s", s)
	}
	if !(pkgIdx < importIdx && importIdx < methodIdx) {
		t.Fatalf("usecase.go sections out of order (package=%d import=%d method=%d):\n---\n%s", pkgIdx, importIdx, methodIdx, s)
	}
	for _, want := range []string{
		`pb "example.com/demo/kitex_gen/demo"`,
		`goerror "github.com/byx-darwin/go-tools/go-common/error"`,
		"func (uc *UseCase) Ping(ctx context.Context, req *pb.PingReq) (resp *pb.PingResp, err error) {",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("usecase.go missing %q\n---\n%s", want, s)
		}
	}
}

func TestAddRPCHzAppendsSignature(t *testing.T) {
	root := seedRPCProject(t, manifest.KindHertz,
		"internal/handler/pb/handler.go", hzHandlerFixture, minimalUsecaseGo)

	res, err := AddRPC(RPCOptions{Root: root, Service: "demo", RPC: "Ping"})
	if err != nil {
		t.Fatalf("AddRPC: %v", err)
	}
	body, err := os.ReadFile(res.Path)
	if err != nil {
		t.Fatalf("read usecase: %v", err)
	}
	s := string(body)
	for _, want := range []string{
		`pb "example.com/demo/internal/pb"`,
		"func (uc *UseCase) Ping(ctx context.Context, req *pb.PingReq) (resp *pb.PingResp, err error) {",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("usecase.go missing %q\n---\n%s", want, s)
		}
	}
}

func TestAddRPCRejectsServiceMismatch(t *testing.T) {
	root := seedRPCProject(t, manifest.KindKitex,
		"internal/handler/demo/handler.go", kitexHandlerFixture, minimalUsecaseGo)
	_, err := AddRPC(RPCOptions{Root: root, Service: "other", RPC: "Ping"})
	if err == nil || !strings.Contains(err.Error(), "does not match manifest service") {
		t.Fatalf("err = %v, want service mismatch error", err)
	}
}

func TestAddRPCRejectsUnknownMethod(t *testing.T) {
	root := seedRPCProject(t, manifest.KindKitex,
		"internal/handler/demo/handler.go", kitexHandlerFixture, minimalUsecaseGo)
	_, err := AddRPC(RPCOptions{Root: root, Service: "demo", RPC: "Missing"})
	if err == nil || !strings.Contains(err.Error(), "not found") {
		t.Fatalf("err = %v, want not-found error", err)
	}
}

func TestAddRPCRejectsDuplicateMethod(t *testing.T) {
	root := seedRPCProject(t, manifest.KindKitex,
		"internal/handler/demo/handler.go", kitexHandlerFixture, minimalUsecaseGo)
	if _, err := AddRPC(RPCOptions{Root: root, Service: "demo", RPC: "Ping"}); err != nil {
		t.Fatalf("first AddRPC: %v", err)
	}
	_, err := AddRPC(RPCOptions{Root: root, Service: "demo", RPC: "Ping"})
	if err == nil || !strings.Contains(err.Error(), "already exists") {
		t.Fatalf("err = %v, want already-exists error", err)
	}
}
