package ai

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/byx-darwin/ncgo/internal/manifest"
)

// target describes one rendered artifact.
type target struct {
	RelPath string
	Render  func(body string) string
}

// targets returns the static set of artifacts produced by `ncgo ai sync`.
// docs/ai-context/architecture.md (PRD §6 row 4) is intentionally
// deferred until ncgo can scan domain port signatures via go/parser.
func targets() []target {
	return []target{
		{RelPath: "AGENTS.md", Render: renderAgents},
		{RelPath: "CLAUDE.md", Render: renderClaude},
		{RelPath: ".cursor/rules/ncgo.mdc", Render: renderCursorMDC},
	}
}

// buildBody assembles the markdown body shared across every target:
// manifest summary + embedded design doc body + optional local notes.
func buildBody(m *manifest.Manifest, opts Options) (string, error) {
	doc, err := readDesignDoc(m.Service.Kind, opts.Lang)
	if err != nil {
		return "", err
	}
	local, err := readLocalNotes(opts.Root)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	writeManifestSummary(&b, m)
	b.WriteString("\n## Architecture & Built-in Features\n\n")
	b.WriteString(stripFirstHeading(doc))
	if strings.TrimSpace(local) != "" {
		b.WriteString("\n## Local Notes\n\n")
		b.WriteString(strings.TrimRight(local, "\n"))
		b.WriteString("\n")
	}
	return b.String(), nil
}

// writeManifestSummary emits the manifest block consumed by AI agents.
func writeManifestSummary(b *strings.Builder, m *manifest.Manifest) {
	fmt.Fprintf(b, "## Manifest\n\n")
	fmt.Fprintf(b, "- module: `%s`\n", m.Module)
	fmt.Fprintf(b, "- service.name: `%s`\n", m.Service.Name)
	fmt.Fprintf(b, "- service.kind: `%s`\n", m.Service.Kind)
	fmt.Fprintf(b, "- service.with_database: `%t`\n", m.Service.WithDatabase)
	if m.Service.IDL != "" {
		fmt.Fprintf(b, "- service.idl: `%s`\n", m.Service.IDL)
	}
	fmt.Fprintf(b, "- mode: `%s`\n", m.Mode)
	if len(m.Infra) > 0 {
		fmt.Fprintf(b, "- infra: `[%s]`\n", strings.Join(m.Infra, ", "))
	}
	if len(m.Domains) > 0 {
		fmt.Fprintf(b, "- domains: `[%s]`\n", strings.Join(m.Domains, ", "))
	}
	fmt.Fprintf(b, "- ncgo: `%s` (assets `%s`)\n", m.Ncgo.Version, m.Ncgo.AssetsVersion)
}

// stripFirstHeading drops the first H1 line so the design doc body can
// be embedded under our own H1 without duplication.
func stripFirstHeading(doc string) string {
	doc = strings.TrimLeft(doc, "\n")
	if !strings.HasPrefix(doc, "# ") {
		return doc
	}
	if i := strings.Index(doc, "\n"); i >= 0 {
		return strings.TrimLeft(doc[i+1:], "\n")
	}
	return ""
}

// renderAgents produces AGENTS.md (universal agent context).
func renderAgents(body string) string {
	var b strings.Builder
	b.WriteString(ManagedMarker + "\n\n")
	b.WriteString("# Project Agent Context\n\n")
	b.WriteString("> Auto-generated by `ncgo ai sync` from `.ncgo/manifest.yaml`\n")
	b.WriteString("> and the embedded ncgo design doc. Do not edit by hand.\n")
	b.WriteString("> User-owned content lives in `AGENTS.local.md` and is\n")
	b.WriteString("> appended below verbatim on every sync.\n\n")
	b.WriteString(body)
	return ensureTrailingNewline(b.String())
}

// renderClaude wraps the same body with a Claude Code preface.
func renderClaude(body string) string {
	var b strings.Builder
	b.WriteString(ManagedMarker + "\n\n")
	b.WriteString("# Project Context for Claude Code\n\n")
	b.WriteString("> Auto-generated by `ncgo ai sync`. The conventions below\n")
	b.WriteString("> come from the embedded ncgo design doc. Follow them when\n")
	b.WriteString("> adding code; the matching review-mode prompts live at\n")
	b.WriteString("> `nc-skills-golang/SKILL.md`.\n\n")
	b.WriteString(body)
	return ensureTrailingNewline(b.String())
}

// renderCursorMDC wraps the body with Cursor's MDC frontmatter so the
// rules engine picks it up for every Go file in the project.
func renderCursorMDC(body string) string {
	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("description: ncgo project rules and architecture (auto-generated)\n")
	b.WriteString("globs: [\"**/*.go\"]\n")
	b.WriteString("alwaysApply: false\n")
	b.WriteString("---\n")
	b.WriteString(ManagedMarker + "\n\n")
	b.WriteString("# Project Rules (ncgo)\n\n")
	b.WriteString("> Auto-generated by `ncgo ai sync`. Cursor consumes these\n")
	b.WriteString("> rules whenever it edits a Go file in this project.\n\n")
	b.WriteString(body)
	return ensureTrailingNewline(b.String())
}

// isManaged reports whether the given file body carries the managed
// marker on (or near) its first content line. We search the first 4
// non-blank lines so MDC frontmatter does not hide the marker.
func isManaged(content []byte) bool {
	scanned := 0
	for _, line := range bytes.Split(content, []byte("\n")) {
		trimmed := bytes.TrimSpace(line)
		if len(trimmed) == 0 {
			continue
		}
		if bytes.Contains(trimmed, []byte(ManagedMarker)) {
			return true
		}
		scanned++
		if scanned >= 6 {
			return false
		}
	}
	return false
}

func ensureTrailingNewline(s string) string {
	if strings.HasSuffix(s, "\n") {
		return s
	}
	return s + "\n"
}
