package importer

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/byx-darwin/ncgo/internal/manifest"
)

func mustWriteFile(t *testing.T, path string, data []byte) {
	t.Helper()
	if err := os.WriteFile(path, data, 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func mustMkdirAll(t *testing.T, path string) {
	t.Helper()
	if err := os.MkdirAll(path, 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", path, err)
	}
}

func TestDetectModule(t *testing.T) {
	t.Run("extracts module path from go.mod", func(t *testing.T) {
		dir := t.TempDir()
		mustWriteFile(t, filepath.Join(dir, "go.mod"), []byte("module github.com/test/myapp\n\ngo 1.25\n"))
		got, err := detectModule(dir)
		if err != nil {
			t.Fatalf("detectModule() error = %v", err)
		}
		if got != "github.com/test/myapp" {
			t.Fatalf("detectModule() = %q, want %q", got, "github.com/test/myapp")
		}
	})

	t.Run("errors when go.mod is missing", func(t *testing.T) {
		empty := t.TempDir()
		_, err := detectModule(empty)
		if err == nil {
			t.Fatal("detectModule() should error when go.mod is missing")
		}
	})

	t.Run("errors when go.mod has no module directive", func(t *testing.T) {
		d := t.TempDir()
		mustWriteFile(t, filepath.Join(d, "go.mod"), []byte("go 1.25\n"))
		_, err := detectModule(d)
		if err == nil {
			t.Fatal("detectModule() should error when no module directive")
		}
		if !strings.Contains(err.Error(), "module directive not found") {
			t.Fatalf("error = %q, want 'module directive not found'", err.Error())
		}
	})
}

func TestDetectKind(t *testing.T) {
	t.Run("detects hertz from router.go marker", func(t *testing.T) {
		dir := t.TempDir()
		mustWriteFile(t, filepath.Join(dir, "router.go"), []byte("// Code generated by hz. DO NOT EDIT.\npackage main\n"))
		got, err := detectKind(dir)
		if err != nil {
			t.Fatalf("detectKind() error = %v", err)
		}
		if got != manifest.KindHertz {
			t.Fatalf("detectKind() = %q, want %q", got, manifest.KindHertz)
		}
	})

	t.Run("detects kitex from handler.go marker", func(t *testing.T) {
		dir := t.TempDir()
		mustWriteFile(t, filepath.Join(dir, "handler.go"), []byte("// Code generated by kitex. DO NOT EDIT.\npackage main\n"))
		got, err := detectKind(dir)
		if err != nil {
			t.Fatalf("detectKind() error = %v", err)
		}
		if got != manifest.KindKitex {
			t.Fatalf("detectKind() = %q, want %q", got, manifest.KindKitex)
		}
	})

	t.Run("errors when neither marker is found", func(t *testing.T) {
		dir := t.TempDir()
		_, err := detectKind(dir)
		if err == nil {
			t.Fatal("detectKind() should error when no markers found")
		}
		if !strings.Contains(err.Error(), "cannot detect service kind") {
			t.Fatalf("error = %q, want 'cannot detect service kind'", err.Error())
		}
	})
}

func TestDetectServiceName(t *testing.T) {
	t.Run("from IDL file", func(t *testing.T) {
		dir := t.TempDir()
		mustMkdirAll(t, filepath.Join(dir, "idl", "app"))
		mustWriteFile(t, filepath.Join(dir, "idl", "app", "user-api.proto"), []byte("syntax = \"proto3\";\n"))
		got, err := detectServiceName(dir, manifest.KindHertz)
		if err != nil {
			t.Fatalf("detectServiceName() error = %v", err)
		}
		if got != "user-api" {
			t.Fatalf("detectServiceName() = %q, want %q", got, "user-api")
		}
	})

	t.Run("fallback to directory name", func(t *testing.T) {
		dir := t.TempDir()
		sub := filepath.Join(dir, "myfallback")
		mustMkdirAll(t, sub)
		got, err := detectServiceName(sub, manifest.KindHertz)
		if err != nil {
			t.Fatalf("detectServiceName() error = %v", err)
		}
		if got != "myfallback" {
			t.Fatalf("detectServiceName() = %q, want %q", got, "myfallback")
		}
	})
}

func TestDetect(t *testing.T) {
	t.Run("dry preview shape for hertz project", func(t *testing.T) {
		dir := t.TempDir()
		mustWriteFile(t, filepath.Join(dir, "go.mod"), []byte("module github.com/test/myapp\n\ngo 1.25\n"))
		mustWriteFile(t, filepath.Join(dir, "router.go"), []byte("// Code generated by hz. DO NOT EDIT.\npackage main\n"))

		m, err := Detect(Options{Root: dir, NCGOVersion: "0.1.0-test", AssetsVersion: "assets-test"})
		if err != nil {
			t.Fatalf("Detect: %v", err)
		}
		if m.Module != "github.com/test/myapp" {
			t.Fatalf("Module = %q, want %q", m.Module, "github.com/test/myapp")
		}
		if m.Service.Kind != manifest.KindHertz {
			t.Fatalf("Service.Kind = %q, want %q", m.Service.Kind, manifest.KindHertz)
		}
		if m.Mode != manifest.ModeMono {
			t.Fatalf("Mode = %q, want %q", m.Mode, manifest.ModeMono)
		}
		if m.Ncgo.Version != "0.1.0-test" || m.Ncgo.AssetsVersion != "assets-test" {
			t.Fatalf("Ncgo = %+v, want version/assets test values", m.Ncgo)
		}
	})

	t.Run("errors when manifest already exists", func(t *testing.T) {
		dir := t.TempDir()
		mustWriteFile(t, filepath.Join(dir, "go.mod"), []byte("module github.com/test/myapp\n\ngo 1.25\n"))
		mustMkdirAll(t, filepath.Join(dir, ".ncgo"))
		mustWriteFile(t, filepath.Join(dir, ".ncgo", "manifest.yaml"), []byte("ncgo:\n  version: 0.1.0-dev\n"))

		_, err := Detect(Options{Root: dir})
		if err == nil {
			t.Fatal("Detect should reject when manifest already exists")
		}
		if !strings.Contains(err.Error(), "manifest already exists") {
			t.Fatalf("error = %q, want 'manifest already exists'", err.Error())
		}
	})

	t.Run("errors when go.mod is missing", func(t *testing.T) {
		dir := t.TempDir()
		_, err := Detect(Options{Root: dir})
		if err == nil {
			t.Fatal("Detect should reject when go.mod is missing")
		}
		if !strings.Contains(err.Error(), "go.mod not found") {
			t.Fatalf("error = %q, want 'go.mod not found'", err.Error())
		}
	})

	t.Run("errors on invalid explicit kind", func(t *testing.T) {
		dir := t.TempDir()
		mustWriteFile(t, filepath.Join(dir, "go.mod"), []byte("module github.com/test/myapp\n\ngo 1.25\n"))
		_, err := Detect(Options{Root: dir, Kind: "grpc"})
		if err == nil {
			t.Fatal("Detect should reject invalid Kind")
		}
		if !strings.Contains(err.Error(), "invalid") {
			t.Fatalf("error = %q, want 'invalid'", err.Error())
		}
	})
}
