// Package importer detects an existing Hertz/Kitex project's manifest fields
// without writing anything to disk. internal/cli's `ncgo import` command and
// internal/mcp's `ncgo_import` tool both build on Detect.
package importer

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/byx-darwin/ncgo/internal/manifest"
)

// Options configures Detect.
type Options struct {
	Root          string
	Kind          string // auto-detected if empty
	NCGOVersion   string
	AssetsVersion string
}

// Detect inspects an existing Go project at opts.Root and builds the
// manifest.Manifest that `ncgo import` would write, without saving it. It
// rejects roots that already have a manifest or lack a go.mod. Kind is
// auto-detected from generator marker files (router.go for Hertz,
// handler.go for Kitex) when opts.Kind is empty.
func Detect(opts Options) (*manifest.Manifest, error) {
	root, err := filepath.Abs(opts.Root)
	if err != nil {
		return nil, fmt.Errorf("resolve root: %w", err)
	}

	manifestPath := manifest.Path(root)
	if _, err := os.Stat(manifestPath); err == nil {
		return nil, fmt.Errorf("manifest already exists at %s; remove it first or edit it manually", manifestPath)
	}

	goModPath := filepath.Join(root, "go.mod")
	if _, err := os.Stat(goModPath); os.IsNotExist(err) {
		return nil, fmt.Errorf("go.mod not found at %s; this command requires an existing Go module", goModPath)
	}

	module, err := detectModule(root)
	if err != nil {
		return nil, err
	}

	kind := opts.Kind
	if kind == "" {
		kind, err = detectKind(root)
		if err != nil {
			return nil, err
		}
	} else if kind != manifest.KindHertz && kind != manifest.KindKitex {
		return nil, fmt.Errorf("--kind %q is invalid (hertz|kitex)", kind)
	}

	serviceName, err := detectServiceName(root, kind)
	if err != nil {
		return nil, err
	}

	idlPath := detectIDLPath(root, serviceName)

	return &manifest.Manifest{
		Ncgo: manifest.Meta{
			Version:       opts.NCGOVersion,
			AssetsVersion: opts.AssetsVersion,
		},
		Mode:   manifest.ModeMono,
		Module: module,
		Service: manifest.Service{
			Name:         serviceName,
			Kind:         kind,
			WithDatabase: false,
			IDL:          idlPath,
		},
	}, nil
}

// detectModule reads the first "module" directive from go.mod.
func detectModule(root string) (string, error) {
	f, err := os.Open(filepath.Join(root, "go.mod"))
	if err != nil {
		return "", err
	}
	defer func() { _ = f.Close() }()
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "module ")), nil
		}
	}
	if err := scanner.Err(); err != nil {
		return "", fmt.Errorf("read go.mod: %w", err)
	}
	return "", fmt.Errorf("module directive not found in go.mod")
}

// detectKind inspects source markers to determine whether the project is
// Hertz or Kitex.
func detectKind(root string) (string, error) {
	if isHertzProject(filepath.Join(root, "router.go")) {
		return manifest.KindHertz, nil
	}
	if isKitexProject(filepath.Join(root, "handler.go")) {
		return manifest.KindKitex, nil
	}
	return "", fmt.Errorf("cannot detect service kind: no router.go (hz marker) or handler.go (kitex marker) found; use --kind to specify")
}

func isHertzProject(path string) bool {
	b, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return strings.Contains(string(b), "// Code generated by hz.")
}

func isKitexProject(path string) bool {
	b, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return strings.Contains(string(b), "// Code generated by kitex.")
}

// detectServiceName tries to extract the service name from IDL files first,
// then from source code patterns, then falls back to the directory name.
func detectServiceName(root string, kind string) (string, error) {
	idlPath := detectIDLPath(root, "")
	if idlPath != "" {
		if name := serviceNameFromIDL(idlPath); name != "" {
			return name, nil
		}
	}
	switch kind {
	case manifest.KindHertz:
		if name := serviceNameFromHertz(root); name != "" {
			return name, nil
		}
	case manifest.KindKitex:
		if name := serviceNameFromKitex(root); name != "" {
			return name, nil
		}
	}
	return filepath.Base(root), nil
}

func serviceNameFromIDL(idlPath string) string {
	base := filepath.Base(idlPath)
	ext := filepath.Ext(base)
	name := strings.TrimSuffix(base, ext)
	name = strings.TrimPrefix(name, "service_")
	return name
}

// serviceNameFromHertz tries to extract the service name from router.go's
// import paths or registration patterns.
func serviceNameFromHertz(root string) string {
	b, err := os.ReadFile(filepath.Join(root, "router.go"))
	if err != nil {
		return ""
	}
	content := string(b)
	re := regexp.MustCompile(`"\S+/biz/router"`)
	match := re.FindString(content)
	if match != "" {
		match = strings.Trim(match, `"`)
		parts := strings.Split(match, "/")
		for i, p := range parts {
			if p == "biz" && i > 0 {
				return parts[i-1]
			}
		}
	}
	return ""
}

// serviceNameFromKitex tries to extract the service name from handler.go's
// NewServer call: <ServiceName>.NewServer(.
func serviceNameFromKitex(root string) string {
	b, err := os.ReadFile(filepath.Join(root, "handler.go"))
	if err != nil {
		return ""
	}
	content := string(b)
	re := regexp.MustCompile(`(\w+)\.NewServer\(`)
	matches := re.FindStringSubmatch(content)
	if len(matches) >= 2 {
		return matches[1]
	}
	return ""
}

// detectIDLPath searches the idl/ directory for .proto or .thrift files.
// If serviceName is non-empty, prioritizes idl/app/<name>.proto.
func detectIDLPath(root string, serviceName string) string {
	if serviceName != "" {
		candidates := []string{
			filepath.Join("idl", "app", serviceName+".proto"),
			filepath.Join("idl", "app", serviceName+".thrift"),
			filepath.Join("idl", serviceName+".proto"),
			filepath.Join("idl", serviceName+".thrift"),
		}
		for _, c := range candidates {
			if _, err := os.Stat(filepath.Join(root, c)); err == nil {
				return c
			}
		}
	}
	var found string
	idlDir := filepath.Join(root, "idl")
	err := filepath.WalkDir(idlDir, func(path string, d os.DirEntry, walkErr error) error {
		if walkErr != nil || found != "" {
			return nil
		}
		if d.IsDir() {
			return nil
		}
		ext := filepath.Ext(d.Name())
		if ext == ".proto" || ext == ".thrift" {
			rel, relErr := filepath.Rel(root, path)
			if relErr == nil {
				found = rel
			}
		}
		return nil
	})
	if err != nil {
		return ""
	}
	return found
}
