// Code initially generated by ncgo add domain. Edit freely; ncgo will not
// overwrite this file unless --force is passed.
//
// ncgo:domain=user_profile kind=register
package data

import (
	"github.com/samber/do"

	user_profilerepo "github.com/x/demo/internal/repository/user_profile"
	user_profileuc "github.com/x/demo/internal/usecase/user_profile"
)

// RegisterUserProfile wires the user_profile domain (repository + usecase) into the injector.
// Call this once during application bootstrap, before resolving handlers.
//
// ncgo:domain=user_profile kind=register
func RegisterUserProfile(injector *do.Injector) {
	do.Provide(injector, func(i *do.Injector) (user_profilerepo.Repository, error) {
		return user_profilerepo.NewStub(), nil
	})
	do.Provide(injector, func(i *do.Injector) (*user_profileuc.UseCase, error) {
		return user_profileuc.New(do.MustInvoke[user_profilerepo.Repository](i)), nil
	})
}
